### ISSUE TITLE
Incomplete build from source instructions 

### ISSUE THREAD

**Issue by machitgarha** [mahancoder/Adobe-Connect-Linux#2]
First of all, thanks for this cool work!

It seems the documentation for building from source is somehow incomplete. I tried two times, and had to manually install 64-bit version of CEF, and copy the shared library `libcef.so` to the install path (which, might be an incompatible version of the library).

What I guess is, first it must be mentioned that people clone the repository with `--recursive` option, so the submodule under CEF/ directory becomes available, and second there must be a building process of the library, so the `libcef.so`, for instance, be built (perhaps an edit to `make.sh`?).

**Comment by mahancoder** [comment]
Hi, thanks for the report. First of all, the make script is supposed to automatically download and place CEF binaries into the created Release folder, I will double-check it to see if everything is fine. And, the submodule is only there to include CEF copyright licensing, and plays no role in the actual code, since the make script will get the binaries from the CEF binary distribution.

**Comment by mahancoder** [comment]
Update: I just tested the build from scratch by cloning the repo on a new machine. Everything worked fine as expected and the generated `Release` folder contained everything necessary, including the CEF binaries. Perhaps you are having another issue? Are there any errors during the build script?

**Comment by machitgarha** [comment]
@mahancoder, good points. Then I have to test it again, maybe tomorrow, with a clean environment. I'll report back.

Thanks for your reply.

**Comment by mahancoder** [comment]
No problem, let me know about the results.

**Comment by machitgarha** [comment]
My bad. I was not aware of the `Release` directory. Thanks for your help.
